### ISSUE TITLE
Is `composes` supposed to work?

### ISSUE THREAD

**Issue by bitttttten** [gajus/babel-plugin-react-css-modules#192] opened 2018-07-27 16:28 UTC
```css
/* PageTitle.css */
.root {
	composes: h2 from '../../theme/type.css';
	color: #147C3F;
	padding: 1.6rem 0;
}
```

```css
/* theme/type.css */
.heading {
	line-height: 1.2em;
	text-align: center;
	font-weight: bold;
	letter-spacing: 0.8px;
	text-transform: uppercase;
}

.h2 {
	composes: heading;
	font-size: 2.4rem;
}
```

My class name is correct: `<h2 class="PageTitle_root theme_h2 theme_heading">Shopping</h2>`. However the CSS is not:
```css
/* theme/type.css */
._2mTJYElVgbS7n2ZX_6poxK{line-height:1.2em;text-align:center;font-weight:700;letter-spacing:.8px;text-transform:uppercase}
.euz7EGBHQkfc-E5dtLq7b{font-size:38.4px;font-size:2.4rem}

/* PageTitle.css */
.PageTitle_root{color:#147c3f;padding:25.6px 0;padding:1.6rem 0}
```

As you can see, the PageTitle CSS is generating the class name correctly, but the theme/type.css file is not. What's up with that?

My config is this:

```js
// Process JS with Babel.
{
	test: /\.(js|jsx|mjs)$/,
	include: paths.appSrc,
	loader: require.resolve('babel-loader'),
	options: {
		// This is a feature of `babel-loader` for webpack (not Babel itself).
		// It enables caching results in ./node_modules/.cache/babel-loader/
		// directory for faster rebuilds.
		cacheDirectory: false,
		plugins: [
			'transform-decorators-legacy',
			'react-loadable/babel',
			['react-css-modules', {
				context: paths.appSrc,
				generateScopedName,
				webpackHotModuleReloading: false,
				attributeNames: {
					activeStyleName: 'activeClassName'
				}
			}]
		]
	},
},
```

**Comment by gajus** [comment] 2018-07-27 17:16
Whats the definition of `generateScopedName`?

**Comment by bitttttten** [comment] 2018-07-28 06:38
And also my css-loader config:

```js
{
	test: /\.css$/,
	use: [
		{
			loader: require.resolve('style-loader'),
			options: {
				insertInto: 'body',
			},
		},              
		{
			loader: require.resolve('css-loader'),
			options: {
				importLoaders: 1,
				modules: true,
				getLocalIdent: (context, localIdentName, localName) => {
					return generateScopedName(localName, context.resourcePath)
				},
			},
		},
		{
			loader: require.resolve('postcss-loader'),
		},
	],
},
```

**Comment by bitttttten** [comment] 2018-08-08 19:19
Perhaps it is my local set up that is incorrect. If I remove `getLocalIdent` from the css-loader and `generateScopedName` from react-css-modules config my css is not working at all.

I see in the DOM:

`<h2 class="components-PageTitle-___PageTitle__root___3fA2n theme-___type__h2___266vk theme-___type__heading___1anDN">Shopping</h2>`

But in the CSS I see:

`/* PageTitle.css */._3fA2nPANa1DNO1QapNXW1v{color:#147c3f;padding:25.6px 0;padding:1.6rem 0}`

If you are still interested, I can give you a repo to check out?

**Comment by gajus** [comment] 2018-11-27 09:34
Probably duplicate of:

* https://github.com/gajus/babel-plugin-react-css-modules/issues/48 or
* https://github.com/gajus/babel-plugin-react-css-modules/issues/22

**Closed by gajus** 2018-11-27 09:34 UTC
Labels: question
