### ISSUE TITLE
runtime resoluton won't work with composes

### ISSUE THREAD

**Issue by loadingwyn** [gajus/babel-plugin-react-css-modules#113] opened 2017-07-20 12:08 UTC
jsx
```js
  <div styleName={type === 'article' ? 'article-card' : 'live-card'}>
```
css:
```css
.search {
    width: 650px;
}
.live-card {
    composes: search;
    white-space: nowrap;
    font-size: 14px;
    line-height: 60px;
    color: #666666;
}
```
I get this:
```html
<div class="reprodStyle_live-card_2j7Qr reprodStyle_four-col_2_FEw"></div>
```
The 'search' class doesn't get added, and the 'four-col' which was composed before is still used.

My environment
---

software | version
-- | --
Babel | 6.24.1
node | 8.1.4
Operating System | windows 10

**Comment by Loading-wyn** [comment] 2017-07-20 12:13
If I reinstall babel-plugin-react-css-modules, everything works fine. But if I change the class which was composed and compile the project again, this problem will happen.

**Comment by richtera** [comment] 2017-08-03 13:36
I have a similar problem when using composed classes. When the composed classes are in the global space it gets a bit worse and shows "undefined" for those composed classes. So there is a bit of a problem using composed classes. It's trying to resolve classNames after the already resolving.
So for example

```javascript
import "./styles.css"
```

Will cause something like this for a composed class

```css
.example {
  composes: btn from '../global.css'
}
```

The resolved styles might be

```javascript
var styles = {
  'example': 'styles-example-ASDEF btn'
};
```

The output will results in

```javascript
<SomeComponent className="styles-example-ASDEF undefined"/>
```

This is because it can't resolve "btn" inside of the stylesheet context but should be looking it up inside of the composed stylesheet or leave it alone altogether. I.e. leave names it can't resolve.

Not sure how to fix this. I switched to straight react-css-modules till then.

**Comment by gajus** [comment] 2017-08-23 07:30
> Not sure how to fix this. I switched to straight react-css-modules till then.

`react-css-modules` will have the same problem.

This is a low-level issue with https://github.com/webpack-contrib/css-loader or more generally with https://github.com/css-modules/css-modules.

**Comment by gajus** [comment] 2017-08-23 07:32
This:

```js
<div class="reprodStyle_live-card_2j7Qr reprodStyle_four-col_2_FEw"></div>

```

Cannot be the output of:

```js
 <div styleName={type === 'article' ? 'article-card' : 'live-card'}>

```

Where is the `four-col` coming from?

**Comment by loading-wyn** [comment] 2017-08-25 16:24
The `four-col` is defined in the same css file. It was composed by `live-card` before.
```
.live-card {
    composes: four-col;
    ...
}
```
And it can't be removedas espected  when `type === 'article'` at runtime. So I change `composes: four-col;` to `composes: four-col;` to locate problem, but `four-col` still stay there.

**Comment by gajus** [comment] 2017-08-25 18:01
This doesn't really make sense.

Is the code repository public/ or could your re-create it in a sandbox?

**Comment by loadingwyn** [comment] 2017-10-09 11:59
@gajus I'm sorry I just notice your reply after such a long time. I think this problem may be caused by `react-dev-utils/webpackHotDevClient`, because it works well when I don't use webpack-dev-server.
You can reproduct it by using `create-react-app`. 

1.  create a react app with `create-react-app`.

2. run `npm run eject`

3.  add `babel-plugin-react-css-modules`

webpack.config.dev.js:

```js
{
            test: /\.css$/,
            use: [
              require.resolve('style-loader'),
              {
                loader: require.resolve('css-loader'),
                options: {
                  importLoaders: 2,
                  localIdentName: '[name]_[local]_[hash:base64:5]',
                  modules: true,
                  camelCase: true,
                },
              },
              {
                loader: require.resolve('postcss-loader'),
                options: {
                  // Necessary for external CSS imports to work
                  // https://github.com/facebookincubator/create-react-app/issues/2677
                  ident: 'postcss',
                  plugins: () => [
                    require('postcss-flexbugs-fixes'),
                    autoprefixer({
                      browsers: [
                        '>1%',
                        'last 4 versions',
                        'Firefox ESR',
                        'not ie < 9', // React doesn't support IE8 anyway
                      ],
                      flexbox: 'no-2009',
                    }),
                  ],
                },
              },
            ],
          },
```

babel:

```
  "babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
      [
          "react-css-modules",
          {
              "webpackHotModuleReloading": true,
              "generateScopedName": "[name]_[local]_[hash:base64:5]",
              "filetypes": {
                  ".scss": {
                      "syntax": "postcss-scss"
                  }
              }
          }
      ]
    ]
  },

```
4. run `npm start`

5. compose selectors while the dev-server is running.

**Comment by gajus** [comment] 2018-11-27 09:33
Probably duplicate of:

* https://github.com/gajus/babel-plugin-react-css-modules/issues/48 or
* https://github.com/gajus/babel-plugin-react-css-modules/issues/22

**Closed by gajus** 2018-11-27 09:33 UTC
Labels: question
