### ISSUE TITLE
v3.3.3 has no configre property: 'attributeNames'

### ISSUE THREAD

**Issue by chenxxzhe** [gajus/babel-plugin-react-css-modules#164] opened 2018-03-09 06:44 UTC
v3.3.3 has no configure property: 'attributeNames'

webpack compile error:
```
      [ { keyword: 'additionalProperties',
          dataPath: '',
          schemaPath: '#/additionalProperties',
          params: { additionalProperty: 'attributeNames' },
          message: 'should NOT have additional properties' } ]
      ✖ ｢wdm｣: Hash: da241e80fefa71cafb5a
      Version: webpack 3.11.0
      Time: 2324ms
```

**Comment by dhlavaty** [comment] 2018-03-12 11:43
Same problem when using `.babelrc`. This is my conf:

```
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 4 chrome versions", "last 4 firefox versions"]
      }
    }], "react", "flow"
  ],
  "plugins": ["transform-object-rest-spread", "transform-class-properties", ["react-css-modules", {
    "context": "./src",
    "generateScopedName": "[name]__[local]___[hash:base64:5]",
    "filetypes": {
      ".scss": {
        "syntax": "postcss-scss"
      }
    },
    "attributeNames": {
      "activeStyleName": "activeClassName"
    }
  }], ],
}
```

and it ends up with error:

```
[ { keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/additionalProperties',
    params: { additionalProperty: 'attributeNames' },
    message: 'should NOT have additional properties' } ]
Error: ./menu.container.js: Invalid configuration
```

**Comment by sundeep-babbur** [comment] 2018-04-10 12:11
Related to https://github.com/gajus/babel-plugin-react-css-modules/issues/174.

**Comment by gajus** [comment] 2018-11-27 09:35
Duplicate of https://github.com/gajus/babel-plugin-react-css-modules/issues/174

**Closed by gajus** 2018-11-27 09:35 UTC
Labels: bug, not confirmed
