### ISSUE TITLE
Composes not working with SCSS files

### ISSUE THREAD

**Issue by shuboc** [gajus/babel-plugin-react-css-modules#85] opened 2017-05-10 06:59 UTC
I am writing `.scss` files which `composes` classes from other files like this:

> a.scss

```css
.a {
  composes: container from './b.css';
}
```

Then I get error messages as follows:

```
Module build failed: CssSyntaxError: /home/shubo/Desktop/babel-plugin-react-css-modules/demo/src/components/AnonymouseStyleResolution.js: postcss-modules-scope: /home/shubo/Desktop/babel-plugin-react-css-modules/demo/src/components/table.scss:4:3: referenced class name "i__imported_container_0" in composes not found
```

I am using `filetypes` options to parse `.scss` files in my webpack config (to keep things simple, I use only css-loader for scss files):

```js
    loaders: [
      {
        include: path.resolve(__dirname, './src'),
        loaders: [
          'style-loader',
          'css-loader?importLoader=1&modules&localIdentName=[path]___[name]__[local]___[hash:base64:5]'
        ],
        test: /\.(css|scss)$/
      },
      {
        include: path.resolve(__dirname, './src'),
        loader: 'babel-loader',
        query: {
          plugins: [
            'transform-react-jsx',
            [
              'react-css-modules',
              {
                context,
                filetypes: {
                  '.scss': 'postcss-scss'
                }
              }
            ]
          ]
        },
        test: /\.js$/
      }
    ]
```

If I modify the config above as `filetypes: {'.scss': ''}`, the error goes away.

My guess is the file (b.css) containing the class being composed with is somehow not properly parsed or loaded. 

Is there any missing postcss configuration I should add or ideas on how to fix it? Thanks in advance.

**Comment by lagun4ik** [comment] 2017-05-26 11:10
> This module does not compile SCSS. It simply parses mixins as custom at-rules & variables as properties, so that PostCSS plugins can then transform SCSS source code alongside CSS.

[postcss-scss](https://github.com/postcss/postcss-scss)

**Comment by dsempel** [comment] 2017-06-07 19:34
`composes` is working for me with SCSS files. Your configuration seems good. Maybe try to import `b.css` somewhere so it is loaded? Or rename to `b.scss`.

**Comment by mmw** [comment] 2017-07-05 18:00
I think you need to set `generateScopedName` in the plugin options. Something like ```
```
...
generateScopedName: "[path]___[name]__[local]___[hash:base64:5]",
fileTypes: {...}
```

**Comment by lagun4ik** [comment] 2017-07-06 08:35
may be

```
  {
    context,
    filetypes: {
      ".scss": {
        "syntax": "postcss-scss",
        "plugins": ["postcss-icss-composes"]
      }
    }
  }
```

**Comment by Dharmoslap** [comment] 2018-03-19 04:13
@shuboc have you managed to resolve this?

**Comment by shuboc** [comment] 2018-03-20 06:51
@Dharmoslap The problem seems to be related to the resolution of paths when using syntax like `composes: XXX from 'path/to/css';`, but I'm not quite sure. Maybe I can keep looking into it and open a PR once I found a solution.

**Comment by gajus** [comment] 2018-11-27 09:31
Probably duplicate of:

* https://github.com/gajus/babel-plugin-react-css-modules/issues/48 or
* https://github.com/gajus/babel-plugin-react-css-modules/issues/22

**Closed by gajus** 2018-11-27 09:31 UTC
Labels: question
