### ISSUE TITLE
Classnames from props never get concatenated with resolved styleName. Replaced instead.

### ISSUE THREAD

**Issue by giorgosavgeris** [gajus/babel-plugin-react-css-modules#242] opened 2019-03-20 12:52 UTC
We want to use HOCs which sent down some classnames like so:

The styleName in `withWarning.js` resolves from loader to a class name which will be passed down. Here assume the resolved className is `withWarning__warning__er3432`
```js
// withWarning.js
import 'styles.scss'; // has inside a class .warning

export default Component => ({warning, ...props}) => {
  let styleNames = '';
  if (warning) {
    styleNames = 'warning';
  }
  return <Component {...props} styleName={styleNames}/>;
};
```

At `prettyText.js` the styleName resolves as `prettyText__pretty__ty3342`. At the same time the component received as a property `className` which previously resolved `withWarning__warning__er3432`. Instead of merging these two classes on the final outcome, only the resolved from styleName is being used and the className from props never gets concatenated unless someone would explicitly declare the `className` on JSX `<div {...props} className={props.className} styleName='pretty' />`. 
```js
// /prettyText.js
import withWarning from './withWarning';
import 'styles.scss'; // has inside a class .pretty

const Text = props => {
  return <div {...props} styleName='pretty' />;
};

export default withWarning(Text);

```

Ending up with something like so:
```js
// index.js
import TextWithWarning from './text.js';

ReactDOM.render(<TextWithWarning warning>Error</TextWithWarning>);

// Expected: <div class='withWarning__warning__er3432 prettyText__pretty__ty3342'>Error</div>
// Got: <div class='prettyText__pretty__ty3342'>Error</div>
```

**Comment by giorgosavgeris** [comment] 2019-03-20 13:29
@gajus  I think this is not an enhancement. It is a bug.

**Comment by gajus** [comment] 2019-03-20 13:31
Is this not a duplicate of https://github.com/gajus/babel-plugin-react-css-modules/issues/44 ?

**Comment by giorgosavgeris** [comment] 2019-03-20 14:01
Maybe, I am not sure.

**Closed** 2019-03-20 14:06 UTC
Labels: bug, help wanted

**Comment by giorgosavgeris** [comment] 2019-03-20 14:10
Issue #44 is open and unresolved from April 2017.

**Comment by gajus** [comment] 2019-03-20 14:53
> Issue #44 is open and unresolved from April 2017. Nobody will pay attention.

Everyone is welcome to contribute, including you.
