### ISSUE TITLE
composes using absolute paths via webpack context doesn't resolve

### ISSUE THREAD

**Issue by hankthewhale** [gajus/babel-plugin-react-css-modules#109] opened 2017-07-07 15:00 UTC
Hey there. So, what I think that I'm observing is that when I use this plugin, I get module build errors because 

```css
.class {
  composes: someclass from shared_styles/colors.css;` 
}
```
now resolves to 

```css
.class {
  composes: someclass from '/user/path/stuff/project/client/components/SomeComponent/SomeComponent/shared_styles/colors.css.';
}
```

 Prior to using this plugin, `composes` was properly using the `context` key in webpack and resolving paths as 

```css
.class {
  composes: someclass from '/user/path/stuff/project/client/shared_styles/colors.css';
}
```

I believe I am setting everything correctly with the plugin. Doing some light logging within the plugin's index.js file, it is traversing and finding the correct `js` files that are attempting to use the `styleName` attribute.

Here is my webpack config for js stuff (shortened for brevity).

```js
const APP_DIR  = path.resolve(__dirname, '../client');
{
  context: APP_DIR
  module: {
    rules: [
      {
        test: /\.js$/,
        include: APP_DIR,
        exclude: /node_modules/,
        use: [{
          loader: 'react-hot-loader/webpack'
        },{
          loader: 'babel-loader',
          options: {
            babelrc: false,
            presets: [
              ['es2015', { 'modules': false }],
              'stage-0',
              'react'
            ],
            plugins: [
              [
                'react-intl', {
                  messagesDir: './i18n/messages',
                  enforceDescriptions: true
                }
              ],[
                'react-css-modules', {
                  context: APP_DIR
                }
              ]
            ]
          }
        }]
      }
    ]
  }
}
```

I am not aliasing anything in webpack and `composes` is resolving from the `context` key without including this plugin. Any guidance here would be appreciated. I'll keep digging too.

Not sure if this is somewhat related to https://github.com/gajus/babel-plugin-react-css-modules/issues/25?

**Comment by hankthewhale** [comment] 2017-07-14 14:00
@gajus any guidance on this one? Sorry if I'm missing something really dumb.

**Comment by SirbyAlive** [comment] 2017-07-18 14:05
I've been stuck on the same problem.
[On fetch in requireCssModule](https://github.com/gajus/babel-plugin-react-css-modules/blob/master/src/requireCssModule.js#L107), the path resolve is used, totally outside of the babel resolver, so no configuration can actually affect how the path is resolved and it is always either looking for the file relatively or absolutely.

**Comment by gajus** [comment] 2018-11-27 09:33
Probably duplicate of:

* https://github.com/gajus/babel-plugin-react-css-modules/issues/48 or
* https://github.com/gajus/babel-plugin-react-css-modules/issues/22

**Closed by gajus** 2018-11-27 09:33 UTC
Labels: question
